name: osrm_text_instructions_dart
description: Text instructions from OSRM route responses
version: 0.0.1
authors:
  - WBT-Solutions <development@wbt-solutions.de>
homepage: https://github.com/wbt-solutions/osrm_text_instructions_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.2
  osrm_dart_sdk:
    path: ../osrm_dart_sdk
    #git: https://github.com/wbt-solutions/osrm_dart_sdk.git

dev_dependencies:
  test: ^1.15.3
